"""
Catálogo oficial de mapas do AimCoachAI.

Cada mapa é relacionado a uma categoria principal e a uma subcategoria.
Este arquivo foi gerado a partir dos nomes únicos encontrados na base.
"""

MAP_CATALOG = {'1w2t smallflicks small 60s': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 '1w2ts Pasu Perfected': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 '1w2ts Pasu Perfected Easy': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 '1w2ts Perfected': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 '1w2ts reload smallflicks slightly larger': {'categoria': 'Target Switching',
                                              'subcategoria': 'Precisão'},
 '1w3ts Pasu Perfected Micro Goated': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 '1w3ts Pasu Perfected Micro Goated Larger': {'categoria': 'Target Switching',
                                              'subcategoria': 'Precisão'},
 '1w3ts reload': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 '1w6ts reload v2': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 '1wall 2targets far smaller denserer': {'categoria': 'Target Switching',
                                         'subcategoria': 'Precisão'},
 '1wall 6targets small': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 '1wall 6targets small Horizontalish': {'categoria': 'Target Switching',
                                        'subcategoria': 'Precisão'},
 'ADJUSTTRACK - VALORANT': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'ADJUSTTRACK - VALORANT 80%': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'ADJUSTTRACK - VALORANT Easy': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'Aimerz+ 1w4ts HF Hard S1': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'Air Angelic 4 Voltaic Easy': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Air Angelic 4 Voltaic Easy 80% (Good Version)': {'categoria': 'Tracking',
                                                   'subcategoria': 'Reativo'},
 'Air Angelic 4 Voltaic Easy 90%': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Air CELESTIAL No UFO Easy': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Air CELESTIAL No UFO Medium': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Air Pure Intermediate': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Air Pure Medium': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Air Spectral Easy': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Air Voltaic Close Long Strafes Very Easy': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Air Voltaic Easy': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Air Voltaic Easy Invincible 4': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Air Voltaic Far Long Strafes Very Easy': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Air Voltaic Invincible 4 Medium': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Amare beanTS': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'B180 Voltaic': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'B180T Voltaic Easy': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'B90TI Iron': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'BeanClick Wide 8 Bots': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'CatClick Medium': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'Centering 90 Easy+ No Strafes': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Controlsphere': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'Controlsphere Click': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'Controlsphere Easy': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'Controlsphere Far Larger': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'Controlsphere Medium': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'Controlsphere OW': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'Controlsphere SuperbAim Viscose': {'categoria': 'Tracking',
                                     'subcategoria': 'Precisão e controle'},
 'Controlsphere rAim Easy': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'Flicker Plaza rAim Easy': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'FloatTS Angelic Easy': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'Floating Heads Timing 400%': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'Floating Heads Timing 400% FIXED': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'Floating Heads Timing 400% Larger': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'Flower 50cm': {'categoria': 'Tracking', 'subcategoria': 'Suave'},
 'GP Close Long Strafes Easy': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'GP Far Long Strafes Easy': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Ground Plaza Sparky V3': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Kindaclose Fast Strafes Iron': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Leapstrafes Control wobin': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'Leaptrack Goated 75% Slightly Larger': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'PGTI Voltaic Easy': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'PGTI Voltaic Easy 80%': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'Pasu Angelic 20% Larger': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'Pasu Voltaic Reload Easy': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'Pistol Strafe Gallery Sparky': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'Plink Palace Easy': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'Pokeball 3 Sphere Hipfire': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'Pokeball Frenzy Auto TE Wide': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'Pokeball Frenzy Auto Wide Wall 4 Targets Small': {'categoria': 'Target Switching',
                                                    'subcategoria': 'Precisão'},
 'Polarized Hell Easy 20% Slower': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'Popcorn MV Intermediate': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'Popcorn MV Medium': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'Pressure Aiming - 10 Targets': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'RawControlSphere': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'RawMouseControl Reload': {'categoria': 'Tracking', 'subcategoria': 'Suave'},
 'Reflex Flick - Mini': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'Reflex Micro++ Flick Horizontalish': {'categoria': 'Clicking',
                                        'subcategoria': 'Estático e flick'},
 'Reflex Micro++ flick reload small': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'SYW (Smooth Your Wrist) FIXED': {'categoria': 'Tracking', 'subcategoria': 'Suave'},
 'Skeet Tracking': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'SmoothBot Invincible Goated': {'categoria': 'Tracking', 'subcategoria': 'Suave'},
 'SmoothBot Perfected': {'categoria': 'Tracking', 'subcategoria': 'Suave'},
 'Smoothbot Iron': {'categoria': 'Tracking', 'subcategoria': 'Suave'},
 'Smoothsphere Viscose': {'categoria': 'Tracking', 'subcategoria': 'Suave'},
 'StaticSwitchingVox Small': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 'Target Acquisition Flick Horizontal Small OwO': {'categoria': 'Clicking',
                                                   'subcategoria': 'Estático e flick'},
 'VT 1w3ts Intermediate S5': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'VT Aether Intermediate S5': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'VT Aether Novice S5 Hard Bot 1 90%': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'VT AngleShot Micro Valorant': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'VT AntiCentering Valorant': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'VT BerryTS Valorant': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'VT Bounceshot Intermediate': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'VT Bounceshot Viscose Medium': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'VT ControlStrafes Valorant': {'categoria': 'Tracking', 'subcategoria': 'Reativo'},
 'VT ControlTS Intermediate S5': {'categoria': 'Target Switching',
                                  'subcategoria': 'Controle e suavidade'},
 'VT Controlsphere Intermediate S5': {'categoria': 'Tracking',
                                      'subcategoria': 'Precisão e controle'},
 'VT Controlsphere Novice S5 Hard': {'categoria': 'Tracking',
                                     'subcategoria': 'Precisão e controle'},
 'VT Controlsphere Viscose': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'VT DotTS Intermediate S5': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 'VT DriftTS Intermediate S5': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'VT EddieTS Intermediate S5': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'VT Floating Heads Intermediate S5': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'VT Floating Heads Viscose Medium': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'VT FloatingDots Valorant': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 'VT FlyTS Intermediate S5': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'VT Frogtagon Intermediate S5': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'VT Ground Intermediate S5': {'categoria': 'Tracking', 'subcategoria': 'Suave'},
 'VT MicroShot Valorant': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'VT Microshot Valorant Smaller': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'VT Miniphase Valorant': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'VT PGT Intermediate S5': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'VT Pasu Intermediate S5': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'VT PeekShot Valorant': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'VT Penta Bounce Intermediate S5': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'VT Popcorn Intermediate S5': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'VT PreciseOrb Intermediate 15% Slower': {'categoria': 'Tracking',
                                           'subcategoria': 'Precisão e controle'},
 'VT PulseShot Valorant': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'VT Raw Control Intermediate S5': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'VT SiniClick Valorant': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'VT SmallFlicks Valorant': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'VT Snake Track Intermediate S5': {'categoria': 'Tracking', 'subcategoria': 'Suave'},
 'VT VarClick Valorant': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'VT skyTS Novice': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'VT ww5t Intermediate S5': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'Valorant One Taps': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'Valorant Small Horizontal Flicks': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 "Valorant Small Horizontal Flicks - Don't Miss! (boON's)": {'categoria': 'Clicking',
                                                             'subcategoria': 'Estático e flick'},
 'Valorant_Small_Flicks': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'VoxTS Click Medium': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'VoxTargetSwitch Click Small': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 'Whisphere': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'Whisphere Small & Slow 75%': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'Whisphere Viscose': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'WhisphereRawControl': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'aimerz+ Static Switching 5 Bot Slightly Larger': {'categoria': 'Target Switching',
                                                    'subcategoria': 'Precisão'},
 'beanTS': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'cloverRawControl Easy': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'cloverRawControl Easy 80% Speed': {'categoria': 'Tracking',
                                     'subcategoria': 'Precisão e controle'},
 'cloverRawControl Viscose 50cm': {'categoria': 'Tracking', 'subcategoria': 'Precisão e controle'},
 'devTS Goated NR Static 5Bot': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 'devTS Goated NR Static Small': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 'devTS Static Click Angelic': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 'domiSwitch Easy': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'eth 1w2tes Micro': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'eth Pasu Micro Medium': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'eth Precise Dots TS 60%': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 'kinTS Voltaic Easy': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'pasu extra small reload horizontal': {'categoria': 'Clicking', 'subcategoria': 'Dinâmico'},
 'psalmTS Viscose Click': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'skyClick Goated Medium': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'tamTargetSwitch Control Hard': {'categoria': 'Target Switching',
                                  'subcategoria': 'Controle e suavidade'},
 'tamTargetSwitch Smooth Easy': {'categoria': 'Target Switching',
                                 'subcategoria': 'Controle e suavidade'},
 'voxTS Voltaic 25% Larger': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'voxTargetClick 20% Small': {'categoria': 'Clicking', 'subcategoria': 'Estático e flick'},
 'voxTargetSwitch 2': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'waldoTS': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 'waldoTS Intermediate': {'categoria': 'Target Switching', 'subcategoria': 'Precisão'},
 'ww2t Voltaic Horizontalish': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'},
 'ww4t Voltaic': {'categoria': 'Target Switching', 'subcategoria': 'Velocidade'}}
